#!/bin/bash

cd /path/to/March-Intensive-Placement;

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn mip.wsgi:application 127.0.0.1:8000
